[project]
name = "usyd-libcal-auto-booking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = ["playwright", "pyotp"]

[tool.uv]
no-cache = true
prerelease = "allow"
preview = true
upgrade = true