[project]
name = "usyd-libcal-auto-booking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = ["playwright", "pyotp"]

[tool.uv]
no-cache = true
prerelease = "allow"
preview = true
python-preference = "only-managed"
upgrade = true