name: usyd-libcal-auto-booking

on:
  schedule:
    - cron: '30 14 * * *' # 00:30 GMT+10 01:30 GMT+11
  workflow_dispatch:

jobs:
  auto_booking:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

    # Step 2: Install uv

      - name: Install uv
        uses: astral-sh/setup-uv@v3

    # Step 3: set up environment variables
      - name: Set up environment variables
        run: |
          echo "UNIKEY=${{ secrets.UNIKEY }}" >> .env
          echo "UNI_PASSWORD=${{ secrets.UNI_PASSWORD }}" >> .env
          echo "UNI_TOPT_CODE=${{ secrets.UNI_TOPT_CODE }}" >> .env

    # Step 4: Run the script
      - name: Run the script
        run: |
          uv sync
          playwright install
          uv run auto_booking.py

