name: Trigger usyd-libcal-auto-booking

on:
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  book_space_1:
    uses: ./.github/workflows/booking.yaml
    with:
      num_days_from_now: 14
      booking_page_url: 'https://usyd.libcal.com/spaces?lid=3330&gid=0&c=0'
      seat_full_xpath: '/html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[10]/td/div/div[2]/div[23]/a/div/div/div'

  book_space_2:
    uses: ./.github/workflows/booking.yaml
    with:
      num_days_from_now: 14
      booking_page_url: 'https://usyd.libcal.com/spaces?lid=3331&gid=0&c=0'
      seat_full_xpath: '/html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[10]/td/div/div[2]/div[27]/a/div/div/div'

  book_space_3:
    uses: ./.github/workflows/booking.yaml
    with:
      num_days_from_now: 2
      booking_page_url: 'https://usyd.libcal.com/spaces?lid=3331&gid=0&c=0'
      seat_full_xpath: '/html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[28]/td/div/div[2]/div[21]/a/div/div/div'

  book_space_4:
    uses: ./.github/workflows/booking.yaml
    with:
      num_days_from_now: 2
      booking_page_url: 'https://usyd.libcal.com/spaces?lid=3331&gid=0&c=0'
      seat_full_xpath: '/html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[28]/td/div/div[2]/div[27]/a/div/div/div'
