name: usyd-libcal-auto-booking

on:
  schedule:
    - cron: '30 14 * * *' # 00:30 GMT+10 01:30 GMT+11
  workflow_dispatch:

jobs:
  auto_booking:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

    # Step 2: Install uv

      - name: Install uv
        uses: astral-sh/setup-uv@v3

    # Step 3: Run the script
      - name: Run the script
        run: |
          uv sync
          uv run -m playwright install --with-deps
          uv run booking.py --unikey ${{ secrets.UNIKEY }} --password ${{ secrets.UNI_PASSWORD }} --totp ${{ secrets.UNI_TOPT_SECRET }} \
          --booking-seats-json-path 'bookings.json'