name: usyd-libcal-auto-booking

on:
  schedule:
    - cron: '30 14 * * *' # 00:30 GMT+10 01:30 GMT+11
  workflow_dispatch:

jobs:
  auto_booking_1:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

    # Step 2: Install uv

      - name: Install uv
        uses: astral-sh/setup-uv@v3

    # Step 3: Run the script
      - name: Run the script
        run: |
          uv sync
          uv run -m playwright install --with-deps
          uv run booking.py --unikey ${{ secrets.UNIKEY }} --password ${{ secrets.UNI_PASSWORD }} --totp ${{ secrets.UNI_TOPT_CODE }} \
          --num-days-from-now 14 --booking-page-url https://usyd.libcal.com/spaces?lid=3330&gid=0&c=0 \
          --seat-full-xpath /html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[10]/td/div/div[2]/div[23]/a/div/div/div
          

  auto_booking_2:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

    # Step 2: Install uv

      - name: Install uv
        uses: astral-sh/setup-uv@v3

    # Step 3: Run the script
      - name: Run the script
        run: |
          uv sync
          uv run -m playwright install --with-deps
          uv run booking.py --unikey ${{ secrets.UNIKEY }} --password ${{ secrets.UNI_PASSWORD }} --totp ${{ secrets.UNI_TOPT_CODE }} \
          --num-days-from-now 14 --booking-page-url https://usyd.libcal.com/spaces?lid=3331&gid=0&c=0 \
          --seat-full-xpath /html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[10]/td/div/div[2]/div[27]/a/div/div/div

  auto_booking_3:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

    # Step 2: Install uv

      - name: Install uv
        uses: astral-sh/setup-uv@v3

    # Step 3: Run the script
      - name: Run the script
        run: |
          uv sync
          uv run -m playwright install --with-deps
          uv run booking.py --unikey ${{ secrets.UNIKEY }} --password ${{ secrets.UNI_PASSWORD }} --totp ${{ secrets.UNI_TOPT_CODE }} \
          --num-days-from-now 2 --booking-page-url https://usyd.libcal.com/spaces?lid=3331&gid=0&c=0 \
          --seat-full-xpath /html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[28]/td/div/div[2]/div[21]/a/div/div/div

  auto_booking_4:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

    # Step 2: Install uv

      - name: Install uv
        uses: astral-sh/setup-uv@v3

    # Step 3: Run the script
      - name: Run the script
        run: |
          uv sync
          uv run -m playwright install --with-deps
          uv run booking.py --unikey ${{ secrets.UNIKEY }} --password ${{ secrets.UNI_PASSWORD }} --totp ${{ secrets.UNI_TOPT_CODE }} \
          --num-days-from-now 2 --booking-page-url https://usyd.libcal.com/spaces?lid=3331&gid=0&c=0 \
          --seat-full-xpath /html/body/div[2]/main/div/div/div/div[3]/div[1]/div[2]/div/table/tbody/tr/td[3]/div/div/div/table/tbody/tr[28]/td/div/div[2]/div[27]/a/div/div/div
